### ISSUE TITLE
bug with options and double run

### ISSUE THREAD

**Issue by alexander-akait** [remarkjs/gulp-remark#5] opened 2016-03-01 13:31 UTC
``` javascript
remark().use(lint)
```

`.remarkrc`

``` json
"plugins": {
        "lint": {
            "list-item-indent": "space"
        }
}
```

First use `remark()` use `.remarkrc` and run `lint` plugin, second `use` double run `lint` plugin, but not get config file `.remarkrc`

**Comment by wooorm** [comment] 2016-03-01 13:36
If you specify `use(lint)` in the code _and_ in a `.remarkrc` file, you’re specifying that the `lint` plug-in runs _twice_. Same as `remark().use(lint).use(lint)`.

I think this is a feature; why do you think it’s a bug?

**Comment by alexander-akait** [comment] 2016-03-01 13:37
@wooorm hm, as possible to run only lint?

**Comment by wooorm** [comment] 2016-03-01 13:38
Yes, by either not specifying it in `.remarkrc`, or not specifying it in `.use(lint)`. Choose one, and you’ll get it once!

**Comment by alexander-akait** [comment] 2016-03-01 13:43
@wooorm good, but if i run `use`, my `.remarkrc` not loaded in remark cli. It is normal? It is not convenient. I have 2 task in gulp, first run before all and lints all files, second render html from markdown. I have 2 separate task for this, because i use watch for lint changing files (i not need to html render).

**Comment by wooorm** [comment] 2016-03-01 13:44
I’m not yet sure what you’re saying, but it sounds like two questions. Could you show me what code you use, what goes wrong, and what you expect?

**Comment by alexander-akait** [comment] 2016-03-01 13:47
@wooorm

``` javascript
'use strict';

var options = require('../options');
var taskConfig = options.get('tasks.remarkLint');

if (!taskConfig.enable) {
    return;
}

var gulp = require('gulp');
var gulpPlumber = require('gulp-plumber');
var gulpRemark = require('gulp-remark');
var remarkLint = require('remark-lint');
var definingConfiguration = require('../lib/defining-configuration');

function remarkLintTask() {
    var config = this.config;

    return gulp
        .src(config.paths.src.globs, config.paths.src.options)
        .pipe(gulpPlumber(config.options.plumber))
        .pipe(gulpRemark().use(remarkLint));
}

gulp.task('remarkLint', definingConfiguration(taskConfig, remarkLintTask));

module.exports = remarkLintTask;
```

Run this task i run twice `lint`, but first get `.remarkrc`, second not get and use default params. Why second `use` not get configuration file?

**Comment by wooorm** [comment] 2016-03-01 13:55
OK, I think this is gulp-remark related, not remark. I don’t know much about gulp. @denysdovhan, can you help here?

**Comment by alexander-akait** [comment] 2016-03-01 14:00
@wooorm @denysdovhan and still I would like to know whether it is possible to run only lint? May be
add `use` for run only need plugin?

``` javascript
var gulpRemarkUse = require('gulp-remark').use;
```

**Comment by denysdovhan** [comment] 2016-03-01 14:34
> I think this is a feature; why do you think it’s a bug?
> — @wooorm 

@evilebottnawi I can't understand too why you think about this as problem. Just use only `.use(plugin, [options])` and define your settings there, or use only `.remarkrc` and define your configs there.

This behavior is OK. It's like you've say _twice_ what to do:
1. Run lint without any parameters (from `gulpfile.js`)
2. Run lint with _these_ specified parameters (from `.remarkrc`)

I think you didn't noticed that you can define options for `remark-lint` from code, as [second paramether of `.use()`](https://github.com/denysdovhan/gulp-remark#options-1).

**Comment by alexander-akait** [comment] 2016-03-01 14:36
@denysdovhan Ok twice it is normal. But define options (for plugins) in code it is not normal and uncomfortable. I work in big command and we created shared config for linting markdown in many own project - options in code it is not solution, it is strange.

**Comment by denysdovhan** [comment] 2016-03-01 14:39
@evilebottnawi why? Don't you define options for postcss-plugins, for example? It's OK.

If you don't like to define your settings in code, use `.remarkignore` instead.

**Comment by alexander-akait** [comment] 2016-03-01 14:39
@denysdovhan postcss-plugins not use .*rc files

**Comment by alexander-akait** [comment] 2016-03-01 14:41
@denysdovhan we use eslint and have .eslintrc shared config for all projects, we use stylelint and have .stylelintrc shared config for all projects, it would be nice to have the same opportunity and the setting remark-lint.

**Comment by wooorm** [comment] 2016-03-01 14:43
> it would be nice to have the same opportunity and the setting remark-lint.

You can! Just remove the `.use(...)` from your code, as I mentioned above:

> Yes, by either not specifying it in .remarkrc, or not specifying it in .use(lint). Choose one, and you’ll get it once!

**Comment by alexander-akait** [comment] 2016-03-01 14:44
@wooorm i need only linting, why run all plugins? My code may contain error and i can stop build on error. In big project i have many linter and first run linter before build.

**Comment by alexander-akait** [comment] 2016-03-01 14:47
Also i use browserSync and pipe all changes. I need run linting on change code, i not need other plugins (not render html)

**Comment by denysdovhan** [comment] 2016-03-01 14:49
@wooorm can `detectRC` option be passed through `gulpRemark({ detectRC: false })`?

**Comment by wooorm** [comment] 2016-03-01 14:51
@evilebottnawi If you don’t need other plug-ins, don’t use other plug-ins. This has nothing to do with your comments or your question.

Look, you provided code twice: first a `.remarkrc` and a `.use(lint)` call, this issue is relating to that and we explained how you can fix your problem. The second time, you provided a gulpfile without `.remarkrc`. Your problem is fixed, from looking at that file.

Now you’re talking about stuff which I haven’t seen code for, and which shouldn’t happen with the code you provided.

@denysdovhan Yes, [source](https://github.com/wooorm/remark/blob/ac63bc3abacf14cf08ca5e2d8f1f8e88a7b9015c/lib/cli/cli.js#L308-L326).

**Comment by alexander-akait** [comment] 2016-03-01 14:56
@wooorm ok i use and run linter once, but second use not get configuration from .remarkrc

``` javascript
gulpRemark({detectRC: false}).use(gulpRemarkLint)
```

I do not understand why you think it is convenient, but I will cite an example of using linters before build - standard workflow in many projects (incidentally `frail` option not working, gulp not exit with error code >0). Many projects have separate repo where store configuration for `eslint`, `stylelint` and etc. And use their in all projects. Hard code options in code it is bad.

**Comment by alexander-akait** [comment] 2016-03-01 15:03
@wooorm @denysdovhan why not create api:

``` javascript
var gulpRemark = require('gulp-remark');
var gulpRemarkUse = require('gulp-remark').use;
```

Where `gulpRemark()` - get `remarkrc` and run all plugins and `gulpRemarkUse(plugin, options)` run only plugin. And why i `use` with plugin, `.remarkrc` not load?

**Comment by wooorm** [comment] 2016-03-01 15:16
@evilebottnawi It seems you’re saying many different things, e.g., `--frail` not working. Please raise separate issues for those (**with your code, what you tried, what you expected, and what happened**).

In your last comment, you’re proposing a mechanism where only one plug-in is run. I do not know of any other similar systems which allow that. Think Babel, which doesn’t allow running one plug-in, or PostCSS, which doesn’t allow just running one plug-in.

Maybe you’re interested in [gulp-remark-lint](https://github.com/davidosomething/gulp-remark-lint-dko)?

**Comment by denysdovhan** [comment] 2016-03-01 15:17
@evilebottnawi if you want, you can use it like this:

``` js
const gulpRemarkUse = require('gulp-remark')().use;
```

And it will do what you need.

**Comment by alexander-akait** [comment] 2016-03-01 15:20
@wooorm postcss plugins not use `.rc` files, rewark add this feature, but if i use only one plugin, options from `.remarkrc` not loaded. it's a bit strange. Thanks for plugin.
@denysdovhan all plugins will work then.

**Comment by wooorm** [comment] 2016-03-01 15:23
Then use `const gulpRemarkUse = require('gulp-remark')({detectRC: false}).use;`

**Comment by alexander-akait** [comment] 2016-03-01 15:24
@wooorm 
I install directry rewark and 

```
remark *.md
```

All options for plugins are loaded

use

```
remark --use remark-lint *.md
```

Options not loaded for plugin from `.remarkrc`. It is really a bit strange. It is normal?

**Comment by wooorm** [comment] 2016-03-01 15:27
Don’t use plug-ins both in `.remarkrc` and in the flags. you’re specifying it to run the same plug-in, by two different names, and thus twice.

**Comment by denysdovhan** [comment] 2016-03-01 15:28
https://github.com/denysdovhan/gulp-remark/issues/5#issuecomment-190769499 about **remark**, not about **gulp-remark**. If you think this is strange, please open an issue there.

Thank you for your question. I'm gonna close this issue, because the problem is solved. If you have any other question, please ask.

P.S: [postcss-cli has config files](https://github.com/code42day/postcss-cli#--config-c).

**Closed as completed by denysdovhan** 2016-03-01 15:28 UTC
Labels: 🙋 no/question
